import { Award, Eye, HeartHandshake, Lightbulb, Target, Users } from "lucide-react";
import { SectionTitle } from "@/components/SectionTitle";
import { team } from "@/data/site";

export default function TentangPage() {
  return <>
    <section className="page-hero"><div className="shell"><span>Tentang Kami</span><h1>Mengenal perjalanan<br />dan orang-orang di baliknya.</h1><p>Kami tumbuh dari keresahan yang sama dan keyakinan bahwa perubahan selalu dimulai dari keberanian untuk peduli.</p></div></section>
    <section className="section shell story-grid"><div><SectionTitle eyebrow="Cerita Kami" title="Berawal dari obrolan sederhana." /><p>IMAJATOS lahir pada 2022 dari sekelompok anak muda yang ingin menghadirkan manfaat nyata di lingkungan terdekat. Langkah pertama kami sederhana: mendengarkan, memahami, lalu bergerak bersama warga.</p><p>Hari ini, semangat itu tumbuh menjadi kolaborasi lintas profesi dan komunitas. Kami tetap memegang satu prinsip: setiap program harus relevan, transparan, dan berkelanjutan.</p></div><div className="timeline-card"><span>2022</span><strong>IMAJATOS berdiri</strong><span>2023</span><strong>Program lintas daerah pertama</strong><span>2024</span><strong>100+ relawan bergabung</strong><span>2026</span><strong>45+ program terlaksana</strong></div></section>
    <section className="values-section section"><div className="shell"><SectionTitle eyebrow="Arah Gerak" title="Visi yang menyatukan, misi yang menggerakkan." centered /><div className="vision-grid"><article><Eye /><span>Visi</span><h3>Masyarakat yang berdaya dan saling menguatkan.</h3><p>Menjadi ruang kolaborasi pemuda yang terpercaya dalam mendorong perubahan sosial berkelanjutan.</p></article><article><Target /><span>Misi</span><h3>Bekerja dekat, berdampak nyata.</h3><ul><li>Mengembangkan program berbasis kebutuhan.</li><li>Memperluas jejaring kolaborasi.</li><li>Mendorong partisipasi aktif generasi muda.</li></ul></article></div><div className="values-row"><div><HeartHandshake /><strong>Empati</strong></div><div><Lightbulb /><strong>Inovasi</strong></div><div><Users /><strong>Kolaborasi</strong></div><div><Award /><strong>Integritas</strong></div></div></div></section>
    <section className="section shell"><SectionTitle eyebrow="Struktur Organisasi" title="Berkenalan dengan tim kami." text="Digerakkan oleh orang-orang yang percaya bahwa kerja baik selalu lebih kuat saat dilakukan bersama." centered /><div className="team-grid">{team.map((person, i) => <article className="team-card" key={person.name}><div className={`avatar avatar-${person.color}`}>{person.initials}</div><span>{i < 2 ? "Pimpinan" : "Pengurus"}</span><h3>{person.name}</h3><p>{person.role}</p></article>)}</div></section>
  </>;
}
