import { Award, Eye, HeartHandshake, Lightbulb, Target, Users } from "lucide-react";
import { SectionTitle } from "@/components/SectionTitle";
import { team } from "@/data/site";

export default function TentangPage() {
  return <>
    <section className="page-hero"><div className="shell"><span>Tentang Kami</span><h1>Mau kenal kami<br />lebih dekat?</h1><p>Kami berangkat dari keresahan yang sama: ingin bikin sesuatu yang benar-benar terasa manfaatnya.</p></div></section>
    <section className="section shell story-grid"><div><SectionTitle eyebrow="Cerita Kami" title="Cerita yang akan ditulis dari perjalanan nyata." /><p>Bagian ini disiapkan untuk sejarah resmi IMAJATOS: alasan organisasi dibentuk, siapa yang memulai, dan peristiwa penting yang membentuk arah geraknya.</p><p>Konten final perlu disusun dari dokumen atau wawancara resmi agar kisah yang tampil akurat dan benar-benar terasa milik IMAJATOS.</p></div><div className="timeline-card timeline-placeholder"><span>01</span><strong>Tahun dan latar belakang berdiri</strong><span>02</span><strong>Program atau tonggak awal</strong><span>03</span><strong>Perkembangan organisasi</strong><span>04</span><strong>Pencapaian terbaru yang terverifikasi</strong></div></section>
    <section className="values-section section"><div className="shell"><SectionTitle eyebrow="Arah Gerak" title="Visi yang menyatukan, misi yang menggerakkan." centered /><div className="vision-grid"><article><Eye /><span>Visi</span><h3>Masyarakat yang berdaya dan saling menguatkan.</h3><p>Menjadi ruang kolaborasi pemuda yang terpercaya dalam mendorong perubahan sosial berkelanjutan.</p></article><article><Target /><span>Misi</span><h3>Bekerja dekat, berdampak nyata.</h3><ul><li>Mengembangkan program berbasis kebutuhan.</li><li>Memperluas jejaring kolaborasi.</li><li>Mendorong partisipasi aktif generasi muda.</li></ul></article></div><div className="values-row"><div><HeartHandshake /><strong>Empati</strong></div><div><Lightbulb /><strong>Inovasi</strong></div><div><Users /><strong>Kolaborasi</strong></div><div><Award /><strong>Integritas</strong></div></div></div></section>
    <section className="section shell"><SectionTitle eyebrow="Struktur Organisasi" title="Berkenalan dengan tim IMAJATOS." text="Nama, foto, dan jabatan berikut akan diperbarui setelah data struktur resmi diterima." centered /><div className="team-grid">{team.map((person, i) => <article className="team-card" key={`${person.role}-${i}`}><div className={`avatar avatar-${person.color}`}>{person.initials}</div><span>Menunggu data resmi</span><h3>{person.name}</h3><p>{person.role}</p></article>)}</div></section>
  </>;
}
